// Drop-in topic library generated for Codex.
// 400 topic starters across 10 categories.

export type TopicCategory =
  | 'flirty'
  | 'interesting'
  | 'topical'
  | 'philosophy'
  | 'silly'
  | 'personal'
  | 'hypothetical'
  | 'discovery'
  | 'hot-takes'
  | 'star-wars';

export interface Topic {
  readonly id: string;
  readonly category: TopicCategory;
  readonly categoryLabel: string;
  readonly prompt: string;
}

export interface TopicSource {
  readonly topics: readonly Topic[];
}

export const TOPIC_CATEGORIES: Record<TopicCategory, string> = {
  flirty: 'Flirty Sparks',
  interesting: 'Interesting Questions',
  topical: 'Modern Life',
  philosophy: 'Deep Chat',
  silly: 'Silly Chaos',
  personal: 'Tiny Dating-App Intel',
  hypothetical: 'Would You Rather',
  discovery: 'Discovery Mode',
  'hot-takes': 'Harmless Hot Takes',
  'star-wars': 'Padawan Lore',
};

export const TOPIC_LIBRARY: TopicSource = {
  topics: [
    {
      id: 'flirty-01',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a tiny green flag that would make you immediately more interested in someone?',
    },
    {
      id: 'flirty-02',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What compliment would actually work on you, instead of making you want to vanish?',
    },
    {
      id: 'flirty-03',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your idea of accidental chemistry?',
    },
    {
      id: 'flirty-04',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the most underrated kind of flirting?',
    },
    {
      id: 'flirty-05',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What song would make a first date feel suspiciously cinematic?',
    },
    {
      id: 'flirty-06',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What small gesture would make you smile against your will?',
    },
    {
      id: 'flirty-07',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your flirting style: smooth, chaotic, oblivious, or legally concerning?',
    },
    {
      id: 'flirty-08',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a date idea that sounds casual but would secretly win you over?',
    },
    {
      id: 'flirty-09',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is one thing someone can do that instantly makes them more attractive?',
    },
    {
      id: 'flirty-10',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your preferred level of romantic nonsense: subtle, dramatic, or full theatre kid?',
    },
    {
      id: 'flirty-11',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would be your signature move if flirting were a low-budget magic show?',
    },
    {
      id: 'flirty-12',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a weirdly specific thing you find charming?',
    },
    {
      id: 'flirty-13',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your favourite kind of eye contact: confident, shy, accidental, or dangerous?',
    },
    {
      id: 'flirty-14',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the best non-cringe way to say, \'I want to see you again\'?',
    },
    {
      id: 'flirty-15',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would make you think, \'Oh no, they are actually cute\'?',
    },
    {
      id: 'flirty-16',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a romantic cliché you secretly hope happens to you?',
    },
    {
      id: 'flirty-17',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your most flirtatious opinion about food?',
    },
    {
      id: 'flirty-18',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a tiny bit of effort that makes someone feel instantly thoughtful?',
    },
    {
      id: 'flirty-19',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would your dating profile say if it was brutally honest but still charming?',
    },
    {
      id: 'flirty-20',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the difference between banter and emotional parkour?',
    },
    {
      id: 'flirty-21',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What kind of message makes you actually want to reply quickly?',
    },
    {
      id: 'flirty-22',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a harmless thing that makes someone seem mysterious?',
    },
    {
      id: 'flirty-23',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would be the title of a rom-com starring your current love life?',
    },
    {
      id: 'flirty-24',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a first-date question that would make you think, \'Okay, this person is fun\'?',
    },
    {
      id: 'flirty-25',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is something romantic that only works if both people are equally ridiculous?',
    },
    {
      id: 'flirty-26',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the most attractive form of confidence?',
    },
    {
      id: 'flirty-27',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your favourite kind of slow-burn connection?',
    },
    {
      id: 'flirty-28',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is one thing that sounds cheesy but would absolutely work on you?',
    },
    {
      id: 'flirty-29',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your ideal \'we just clicked\' moment?',
    },
    {
      id: 'flirty-30',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What tiny sign tells you someone is properly listening?',
    },
    {
      id: 'flirty-31',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is a cute habit you would pretend not to notice but definitely notice?',
    },
    {
      id: 'flirty-32',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your romantic superpower, and what is your romantic design flaw?',
    },
    {
      id: 'flirty-33',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would your crush need to do to earn bonus points instantly?',
    },
    {
      id: 'flirty-34',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the least smooth thing you could say that might still be adorable?',
    },
    {
      id: 'flirty-35',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your favourite kind of playful argument?',
    },
    {
      id: 'flirty-36',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What makes someone feel safe and exciting at the same time?',
    },
    {
      id: 'flirty-37',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What would be your warning label in a dating app, but make it endearing?',
    },
    {
      id: 'flirty-38',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is the best way someone could ask you on a second date?',
    },
    {
      id: 'flirty-39',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What tiny shared ritual would make dating someone feel special?',
    },
    {
      id: 'flirty-40',
      category: 'flirty',
      categoryLabel: TOPIC_CATEGORIES.flirty,
      prompt: 'What is your most specific \'this person might be trouble\' attraction trigger?',
    },
    {
      id: 'interesting-01',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What topic could you talk about for twenty minutes with almost no preparation?',
    },
    {
      id: 'interesting-02',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something normal that becomes fascinating once someone explains it properly?',
    },
    {
      id: 'interesting-03',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What fact feels fake every time you remember it?',
    },
    {
      id: 'interesting-04',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What everyday system is secretly held together by vibes and crossed fingers?',
    },
    {
      id: 'interesting-05',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What skill looks easy until you actually try it?',
    },
    {
      id: 'interesting-06',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a question you wish people asked more often?',
    },
    {
      id: 'interesting-07',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What invention quietly changed human behaviour more than people admit?',
    },
    {
      id: 'interesting-08',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a tiny design choice that makes life noticeably better?',
    },
    {
      id: 'interesting-09',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something people misunderstand because the name is terrible?',
    },
    {
      id: 'interesting-10',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What job sounds boring until you realise the chaos it probably contains?',
    },
    {
      id: 'interesting-11',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is one thing you would love a behind-the-scenes documentary about?',
    },
    {
      id: 'interesting-12',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a piece of knowledge that made you see the world differently?',
    },
    {
      id: 'interesting-13',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is an object you use daily but have no idea how it is really made?',
    },
    {
      id: 'interesting-14',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a mystery you do not need solved because the speculation is better?',
    },
    {
      id: 'interesting-15',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a hobby you respect deeply but probably lack the patience for?',
    },
    {
      id: 'interesting-16',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a technology that feels mundane now but would look like wizardry to your grandparents?',
    },
    {
      id: 'interesting-17',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something humans are weirdly bad at despite doing it constantly?',
    },
    {
      id: 'interesting-18',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is an underrated sign that someone is actually competent?',
    },
    {
      id: 'interesting-19',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a small rule that improves almost every situation?',
    },
    {
      id: 'interesting-20',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a place you have been that felt like it had a hidden story?',
    },
    {
      id: 'interesting-21',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a trend that reveals something interesting about people?',
    },
    {
      id: 'interesting-22',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something you have changed your mind about after learning more?',
    },
    {
      id: 'interesting-23',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a simple question that becomes complicated the longer you think about it?',
    },
    {
      id: 'interesting-24',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a boring-looking object with surprising engineering behind it?',
    },
    {
      id: 'interesting-25',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a cultural habit that would confuse aliens the most?',
    },
    {
      id: 'interesting-26',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something people do for convenience that has quietly reshaped society?',
    },
    {
      id: 'interesting-27',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a problem that sounds small but is actually incredibly hard to solve?',
    },
    {
      id: 'interesting-28',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is the most interesting rabbit hole you have fallen into recently?',
    },
    {
      id: 'interesting-29',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a sound, smell, or place that instantly takes you somewhere else?',
    },
    {
      id: 'interesting-30',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something old-fashioned that deserves a comeback for practical reasons?',
    },
    {
      id: 'interesting-31',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a modern thing that future historians will probably laugh at?',
    },
    {
      id: 'interesting-32',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a public place where you think the best people-watching happens?',
    },
    {
      id: 'interesting-33',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a tiny luxury that has a surprisingly big effect on quality of life?',
    },
    {
      id: 'interesting-34',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is the most interesting way someone has explained their job to you?',
    },
    {
      id: 'interesting-35',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something you thought was simple until adulthood corrected you?',
    },
    {
      id: 'interesting-36',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is a question that tells you a lot about how someone thinks?',
    },
    {
      id: 'interesting-37',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is the strangest thing you have seen become completely normal?',
    },
    {
      id: 'interesting-38',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is an object you would put in a museum of modern life?',
    },
    {
      id: 'interesting-39',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is something that seems inefficient but works because humans are involved?',
    },
    {
      id: 'interesting-40',
      category: 'interesting',
      categoryLabel: TOPIC_CATEGORIES.interesting,
      prompt: 'What is the most underrated form of intelligence?',
    },
    {
      id: 'topical-01',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What modern trend has gone from exciting to mildly exhausting?',
    },
    {
      id: 'topical-02',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What app feature feels like it was invented during a meeting nobody wanted to attend?',
    },
    {
      id: 'topical-03',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the most 2020s sentence you have heard in real life?',
    },
    {
      id: 'topical-04',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What piece of technology makes you feel powerful and slightly monitored?',
    },
    {
      id: 'topical-05',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What modern convenience would make medieval peasants declare you a witch and a genius?',
    },
    {
      id: 'topical-06',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What online debate should be retired with a small plaque and no ceremony?',
    },
    {
      id: 'topical-07',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What current habit will be embarrassing to explain in fifty years?',
    },
    {
      id: 'topical-08',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What thing has subscriptions now that absolutely should not have subscriptions?',
    },
    {
      id: 'topical-09',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the weirdest thing people have collectively decided is normal?',
    },
    {
      id: 'topical-10',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the most dramatic change smartphones made to social life?',
    },
    {
      id: 'topical-11',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What workplace phrase sounds helpful but usually means trouble is approaching?',
    },
    {
      id: 'topical-12',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a modern problem that would sound absurd to someone from the 1990s?',
    },
    {
      id: 'topical-13',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What bit of AI hype makes you excited, and what bit makes you suspicious?',
    },
    {
      id: 'topical-14',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What everyday item deserves a smart version, and what item absolutely does not?',
    },
    {
      id: 'topical-15',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What cultural trend do you respect even though you do not understand it?',
    },
    {
      id: 'topical-16',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a social media habit that needs a gentle intervention?',
    },
    {
      id: 'topical-17',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a modern thing people pretend to enjoy because everyone else is pretending too?',
    },
    {
      id: 'topical-18',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the next ordinary thing you think will become weirdly premium?',
    },
    {
      id: 'topical-19',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a headline format that should be sent to a quiet farm upstate?',
    },
    {
      id: 'topical-20',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the most overdesigned part of modern life?',
    },
    {
      id: 'topical-21',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What modern product has too many lights, sounds, or opinions?',
    },
    {
      id: 'topical-22',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the best and worst thing about always being reachable?',
    },
    {
      id: 'topical-23',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What fashion trend are you willing to defend under oath?',
    },
    {
      id: 'topical-24',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the most suspiciously confident thing a chatbot could say?',
    },
    {
      id: 'topical-25',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a modern convenience you would struggle to give up, even for character development?',
    },
    {
      id: 'topical-26',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is something people call innovation that is mostly just moving buttons around?',
    },
    {
      id: 'topical-27',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the funniest possible use for a smart fridge?',
    },
    {
      id: 'topical-28',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a modern social rule nobody officially announced but everyone somehow knows?',
    },
    {
      id: 'topical-29',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What recent-ish obsession deserves a documentary narrated with unnecessary seriousness?',
    },
    {
      id: 'topical-30',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What thing became worse the moment it got an app?',
    },
    {
      id: 'topical-31',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is one piece of tech that feels like magic when it works and betrayal when it fails?',
    },
    {
      id: 'topical-32',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What modern habit makes us look like background characters in a sci-fi film?',
    },
    {
      id: 'topical-33',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is something everyone says is simple but somehow takes six passwords?',
    },
    {
      id: 'topical-34',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a notification you would happily remove from civilisation?',
    },
    {
      id: 'topical-35',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a modern phrase that instantly makes you tired?',
    },
    {
      id: 'topical-36',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What object has become too confident because it now connects to Wi-Fi?',
    },
    {
      id: 'topical-37',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is the strangest thing people review online?',
    },
    {
      id: 'topical-38',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What is a digital feature that should be judged by a small village council before launch?',
    },
    {
      id: 'topical-39',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What piece of modern etiquette needs clearer rules?',
    },
    {
      id: 'topical-40',
      category: 'topical',
      categoryLabel: TOPIC_CATEGORIES.topical,
      prompt: 'What technology deserves a little thank-you card for improving daily life?',
    },
    {
      id: 'philosophy-01',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is confidence something you build, borrow, or accidentally fake until it becomes real?',
    },
    {
      id: 'philosophy-02',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do people reveal themselves more through what they love or what annoys them?',
    },
    {
      id: 'philosophy-03',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is being chill a personality trait, a coping strategy, or a very elegant disguise?',
    },
    {
      id: 'philosophy-04',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes a person feel genuinely easy to be around?',
    },
    {
      id: 'philosophy-05',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is timing more important than compatibility, or is that just what unlucky people say?',
    },
    {
      id: 'philosophy-06',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is the difference between being honest and being unnecessarily unedited?',
    },
    {
      id: 'philosophy-07',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do you think people change suddenly, slowly, or only when life corners them?',
    },
    {
      id: 'philosophy-08',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is a harmless belief you would still defend with suspicious intensity?',
    },
    {
      id: 'philosophy-09',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is nostalgia useful, dangerous, or just emotional time travel with better lighting?',
    },
    {
      id: 'philosophy-10',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes something feel meaningful rather than merely impressive?',
    },
    {
      id: 'philosophy-11',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Are first impressions mostly instinct, performance, or luck?',
    },
    {
      id: 'philosophy-12',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is a small act of kindness that says more than a grand gesture?',
    },
    {
      id: 'philosophy-13',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do people become braver with age, or just more tired of pretending?',
    },
    {
      id: 'philosophy-14',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is the difference between peace and boredom?',
    },
    {
      id: 'philosophy-15',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is ambition attractive, intimidating, or only good when it comes with self-awareness?',
    },
    {
      id: 'philosophy-16',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What does it mean to really know someone?',
    },
    {
      id: 'philosophy-17',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Can you be too self-aware, or is that just anxiety wearing glasses?',
    },
    {
      id: 'philosophy-18',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes a memory stick: the moment itself or the story you keep telling about it?',
    },
    {
      id: 'philosophy-19',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is it better to be understood deeply by a few people or liked lightly by many?',
    },
    {
      id: 'philosophy-20',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is a lesson you only learn after failing at it personally?',
    },
    {
      id: 'philosophy-21',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Are we more shaped by the people who loved us or the people who misunderstood us?',
    },
    {
      id: 'philosophy-22',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is the difference between solitude and loneliness?',
    },
    {
      id: 'philosophy-23',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is taste a real personality trait or just autobiography in disguise?',
    },
    {
      id: 'philosophy-24',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes a person wise instead of merely experienced?',
    },
    {
      id: 'philosophy-25',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do people need adventure, or do they just need better stories about ordinary life?',
    },
    {
      id: 'philosophy-26',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is a truth that gets easier to accept with age?',
    },
    {
      id: 'philosophy-27',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is forgiveness for the other person, yourself, or the plot?',
    },
    {
      id: 'philosophy-28',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is the difference between being content and settling?',
    },
    {
      id: 'philosophy-29',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do you think happiness is a goal, a side effect, or a suspiciously vague marketing term?',
    },
    {
      id: 'philosophy-30',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What tiny habit reveals someone\'s values more than their words do?',
    },
    {
      id: 'philosophy-31',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is it better to know exactly what you want or stay open to being surprised?',
    },
    {
      id: 'philosophy-32',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes someone feel trustworthy quickly?',
    },
    {
      id: 'philosophy-33',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Do people fall for potential, reality, or the version of someone they meet on a good day?',
    },
    {
      id: 'philosophy-34',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is the most underrated form of courage?',
    },
    {
      id: 'philosophy-35',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Is comfort the enemy of growth, or does growth need somewhere soft to land?',
    },
    {
      id: 'philosophy-36',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What makes a conversation feel like it has depth rather than just volume?',
    },
    {
      id: 'philosophy-37',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Can two people be right in completely different ways?',
    },
    {
      id: 'philosophy-38',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is one thing you think everyone should unlearn?',
    },
    {
      id: 'philosophy-39',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'Does love make people clearer, sillier, or just more committed to bad decisions?',
    },
    {
      id: 'philosophy-40',
      category: 'philosophy',
      categoryLabel: TOPIC_CATEGORIES.philosophy,
      prompt: 'What is a question that makes people more honest without making them defensive?',
    },
    {
      id: 'silly-01',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which household object would be the most unbearable if it became self-aware?',
    },
    {
      id: 'silly-02',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your brain had a loading screen, what useless tip would appear?',
    },
    {
      id: 'silly-03',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What snack has the energy of a tiny dictator?',
    },
    {
      id: 'silly-04',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which animal looks like it knows office gossip?',
    },
    {
      id: 'silly-05',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What normal phrase sounds like a spell if whispered dramatically?',
    },
    {
      id: 'silly-06',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What would your villain origin story be if the stakes were incredibly low?',
    },
    {
      id: 'silly-07',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your sleep schedule had a brand slogan, what would it be?',
    },
    {
      id: 'silly-08',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the least intimidating animal that could still ruin your afternoon?',
    },
    {
      id: 'silly-09',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which food would be the worst motivational speaker?',
    },
    {
      id: 'silly-10',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What object in your home is clearly plotting something?',
    },
    {
      id: 'silly-11',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your mood today was a weather warning, what would it say?',
    },
    {
      id: 'silly-12',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the most dramatic thing you have done for a snack?',
    },
    {
      id: 'silly-13',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which vegetable seems like it has unpaid taxes?',
    },
    {
      id: 'silly-14',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your wardrobe could talk, what would it complain about first?',
    },
    {
      id: 'silly-15',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What would your pet or imaginary pet say in your defence at court?',
    },
    {
      id: 'silly-16',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the weirdest hill a pigeon could choose to die on?',
    },
    {
      id: 'silly-17',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your phone had a personality, what kind of roommate would it be?',
    },
    {
      id: 'silly-18',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is a tiny inconvenience that deserves a movie-trailer voiceover?',
    },
    {
      id: 'silly-19',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which breakfast food would survive best in a medieval battle?',
    },
    {
      id: 'silly-20',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the most suspiciously confident kitchen utensil?',
    },
    {
      id: 'silly-21',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If you had to haunt one supermarket aisle, which one would it be?',
    },
    {
      id: 'silly-22',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What minor problem makes you behave like a Victorian ghost?',
    },
    {
      id: 'silly-23',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which emoji has seen too much?',
    },
    {
      id: 'silly-24',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the worst possible name for a luxury candle?',
    },
    {
      id: 'silly-25',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your inbox was an animal, what would it be and should we be worried?',
    },
    {
      id: 'silly-26',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What would be the theme tune for losing your keys again?',
    },
    {
      id: 'silly-27',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which appliance would be most likely to start a cult?',
    },
    {
      id: 'silly-28',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is a very small event that deserves a national holiday?',
    },
    {
      id: 'silly-29',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If socks disappeared into another dimension, what would their society be like?',
    },
    {
      id: 'silly-30',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which chair in a room is usually the main character?',
    },
    {
      id: 'silly-31',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is your most irrational personal feud with an object?',
    },
    {
      id: 'silly-32',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your calendar could sigh, when would it do it loudest?',
    },
    {
      id: 'silly-33',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What sandwich filling has chaotic energy?',
    },
    {
      id: 'silly-34',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What would your official title be in a kingdom of mild inconvenience?',
    },
    {
      id: 'silly-35',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'Which animal would be the worst therapist but the best listener?',
    },
    {
      id: 'silly-36',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is the funniest possible secret society for bored adults?',
    },
    {
      id: 'silly-37',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If you had a useless superpower based on your last meal, what would it be?',
    },
    {
      id: 'silly-38',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What item should never be given confidence?',
    },
    {
      id: 'silly-39',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'What is your most dramatic opinion about a biscuit?',
    },
    {
      id: 'silly-40',
      category: 'silly',
      categoryLabel: TOPIC_CATEGORIES.silly,
      prompt: 'If your personality were a badly named Wi-Fi network, what would it be called?',
    },
    {
      id: 'personal-01',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a small luxury you take more seriously than most people?',
    },
    {
      id: 'personal-02',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your ideal Sunday if nobody is trying to improve you?',
    },
    {
      id: 'personal-03',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What tiny thing makes you instantly like someone more?',
    },
    {
      id: 'personal-04',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your comfort meal, and does it come with emotional lore?',
    },
    {
      id: 'personal-05',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What are you weirdly competitive about even though no trophy exists?',
    },
    {
      id: 'personal-06',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your most reliable cure for a bad day?',
    },
    {
      id: 'personal-07',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a boring green flag you genuinely value?',
    },
    {
      id: 'personal-08',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a date idea that reveals more than it looks like it should?',
    },
    {
      id: 'personal-09',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What kind of person brings out your best side?',
    },
    {
      id: 'personal-10',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is something you are trying to get better at without making it your whole personality?',
    },
    {
      id: 'personal-11',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your version of a perfect low-pressure evening?',
    },
    {
      id: 'personal-12',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a small routine that keeps you sane?',
    },
    {
      id: 'personal-13',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is one thing people often get wrong about you at first?',
    },
    {
      id: 'personal-14',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a place that feels like a reset button for you?',
    },
    {
      id: 'personal-15',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a personal rule that quietly improves your life?',
    },
    {
      id: 'personal-16',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a song that knows too much about you?',
    },
    {
      id: 'personal-17',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a hobby you would love to have more time for?',
    },
    {
      id: 'personal-18',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What makes you feel most like yourself?',
    },
    {
      id: 'personal-19',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your favourite kind of plan: spontaneous, scheduled, or fake-spontaneous but actually planned?',
    },
    {
      id: 'personal-20',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is one thing that makes a house feel like a home?',
    },
    {
      id: 'personal-21',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your strongest soft opinion?',
    },
    {
      id: 'personal-22',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a skill you are proud of that rarely gets applause?',
    },
    {
      id: 'personal-23',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is something you find calming that other people might find boring?',
    },
    {
      id: 'personal-24',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What do you notice first when you walk into a new place?',
    },
    {
      id: 'personal-25',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a little win you think people should celebrate more?',
    },
    {
      id: 'personal-26',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What kind of humour gets you every time?',
    },
    {
      id: 'personal-27',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a thing you used to dislike but now understand?',
    },
    {
      id: 'personal-28',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your most specific version of being cosy?',
    },
    {
      id: 'personal-29',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is something you are quietly ambitious about?',
    },
    {
      id: 'personal-30',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a compliment you still remember?',
    },
    {
      id: 'personal-31',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is one thing that makes you feel instantly older than you are?',
    },
    {
      id: 'personal-32',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a tiny red flag in yourself that you are weirdly fond of?',
    },
    {
      id: 'personal-33',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is something you will happily overthink?',
    },
    {
      id: 'personal-34',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is the best kind of unexpected message to receive?',
    },
    {
      id: 'personal-35',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a tradition you would like to start?',
    },
    {
      id: 'personal-36',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your personal definition of a good night out?',
    },
    {
      id: 'personal-37',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is your personal definition of a good night in?',
    },
    {
      id: 'personal-38',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is a smell, place, or song that instantly changes your mood?',
    },
    {
      id: 'personal-39',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is something you care about more than people realise?',
    },
    {
      id: 'personal-40',
      category: 'personal',
      categoryLabel: TOPIC_CATEGORIES.personal,
      prompt: 'What is the most \'you\' thing in your camera roll right now?',
    },
    {
      id: 'hypothetical-01',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather always know when someone is lying or always know when dessert is nearby?',
    },
    {
      id: 'hypothetical-02',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather teleport once a week or have perfect hair every day?',
    },
    {
      id: 'hypothetical-03',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you had to teach a masterclass in something deeply unserious, what would it be?',
    },
    {
      id: 'hypothetical-04',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather be famous for one cool thing or anonymously excellent at everything?',
    },
    {
      id: 'hypothetical-05',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If your future self sent one vague warning, what would be the funniest wording?',
    },
    {
      id: 'hypothetical-06',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have dramatic lighting on demand or a theme song when entering rooms?',
    },
    {
      id: 'hypothetical-07',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could mildly patch one law of physics, what quality-of-life update would you ship?',
    },
    {
      id: 'hypothetical-08',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather read minds for one hour or have everyone read your snack opinions for one day?',
    },
    {
      id: 'hypothetical-09',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could make one boring task illegal, what would disappear first?',
    },
    {
      id: 'hypothetical-10',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have unlimited confidence or unlimited battery life?',
    },
    {
      id: 'hypothetical-11',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you had to live inside one shop after closing time, where would you choose?',
    },
    {
      id: 'hypothetical-12',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather be able to pause time for naps or fast-forward through admin?',
    },
    {
      id: 'hypothetical-13',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If one animal had to become your life coach, which animal are you trusting?',
    },
    {
      id: 'hypothetical-14',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have a perfect sense of direction or a perfect sense of timing?',
    },
    {
      id: 'hypothetical-15',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If your life had side quests, what would your current one be?',
    },
    {
      id: 'hypothetical-16',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather only speak in movie quotes or only communicate through suspiciously accurate emojis?',
    },
    {
      id: 'hypothetical-17',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could receive one manual for adulthood, what chapter would you read first?',
    },
    {
      id: 'hypothetical-18',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have a robot assistant with attitude or a ghost assistant with boundaries?',
    },
    {
      id: 'hypothetical-19',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you had to swap lives with a fictional side character for a week, who is least likely to ruin you?',
    },
    {
      id: 'hypothetical-20',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather be able to summon coffee or cancel one meeting per week by magic?',
    },
    {
      id: 'hypothetical-21',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could make one food calorie-free but not healthier, what chaos would you choose?',
    },
    {
      id: 'hypothetical-22',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather be able to find anything you lost or forget anything embarrassing on command?',
    },
    {
      id: 'hypothetical-23',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you had to add one harmless magical rule to society, what would it be?',
    },
    {
      id: 'hypothetical-24',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have every dog like you or every baby stop crying when you enter a room?',
    },
    {
      id: 'hypothetical-25',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you woke up with a tiny crown and no explanation, what would you assume happened?',
    },
    {
      id: 'hypothetical-26',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have free travel forever or free rent forever, but explain your answer dramatically?',
    },
    {
      id: 'hypothetical-27',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could outsource one emotion to a small committee, which one goes first?',
    },
    {
      id: 'hypothetical-28',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have one perfect outfit for every occasion or one perfect comeback for every argument?',
    },
    {
      id: 'hypothetical-29',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If your calendar could grant one wish, what would vanish?',
    },
    {
      id: 'hypothetical-30',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have a warning light for bad decisions or a progress bar for awkward silences?',
    },
    {
      id: 'hypothetical-31',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If one celebrity had to narrate your inner monologue, who would cause the most damage?',
    },
    {
      id: 'hypothetical-32',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have a clone for chores or a clone for social events?',
    },
    {
      id: 'hypothetical-33',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could replace one common object with a luxury version, what becomes absurdly fancy?',
    },
    {
      id: 'hypothetical-34',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather win every argument or never need to argue in the first place?',
    },
    {
      id: 'hypothetical-35',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you could turn one childhood dream into a weekend hobby, what would you pick?',
    },
    {
      id: 'hypothetical-36',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have perfect luck in parking or perfect luck in choosing restaurants?',
    },
    {
      id: 'hypothetical-37',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If everyone had a personal mascot, what would yours be?',
    },
    {
      id: 'hypothetical-38',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather have a rewind button for conversations or a skip button for queues?',
    },
    {
      id: 'hypothetical-39',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'If you had to run a museum of your own life, what exhibit would confuse visitors?',
    },
    {
      id: 'hypothetical-40',
      category: 'hypothetical',
      categoryLabel: TOPIC_CATEGORIES.hypothetical,
      prompt: 'Would you rather know the ending of every film or the true intentions of every group chat?',
    },
    {
      id: 'discovery-01',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something people only learn about you after a few proper conversations?',
    },
    {
      id: 'discovery-02',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a side of you that does not show up well in photos?',
    },
    {
      id: 'discovery-03',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a question that makes you feel genuinely known?',
    },
    {
      id: 'discovery-04',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you are much softer about than people expect?',
    },
    {
      id: 'discovery-05',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one belief you inherited, questioned, and kept anyway?',
    },
    {
      id: 'discovery-06',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a moment that quietly changed your standards?',
    },
    {
      id: 'discovery-07',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you are proud of that you rarely bring up first?',
    },
    {
      id: 'discovery-08',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a trait you admire because it does not come naturally to you?',
    },
    {
      id: 'discovery-09',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What kind of friendship has shaped you the most?',
    },
    {
      id: 'discovery-10',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a lesson you learned later than you wish you had?',
    },
    {
      id: 'discovery-11',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one thing your younger self would be surprised you enjoy now?',
    },
    {
      id: 'discovery-12',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What do you need more of in your life at the moment?',
    },
    {
      id: 'discovery-13',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a fear you have made peace with, at least part-time?',
    },
    {
      id: 'discovery-14',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you want to be known for by the people closest to you?',
    },
    {
      id: 'discovery-15',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a boundary that improved your life?',
    },
    {
      id: 'discovery-16',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a place, person, or habit that helped you become calmer?',
    },
    {
      id: 'discovery-17',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a compliment you find hard to accept but secretly value?',
    },
    {
      id: 'discovery-18',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a tiny sign that you are becoming a better version of yourself?',
    },
    {
      id: 'discovery-19',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you can forgive in others because you understand it in yourself?',
    },
    {
      id: 'discovery-20',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one part of adulthood you are handling better than expected?',
    },
    {
      id: 'discovery-21',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a type of person you are learning to avoid?',
    },
    {
      id: 'discovery-22',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a type of person you are learning to appreciate?',
    },
    {
      id: 'discovery-23',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something that makes you feel grounded quickly?',
    },
    {
      id: 'discovery-24',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a dream you have not fully admitted is still alive?',
    },
    {
      id: 'discovery-25',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a conversation you think everyone should have with themselves once?',
    },
    {
      id: 'discovery-26',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one thing you want more courage for?',
    },
    {
      id: 'discovery-27',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you used to chase that you now let come naturally?',
    },
    {
      id: 'discovery-28',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a personal contradiction you have accepted?',
    },
    {
      id: 'discovery-29',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a mistake that taught you your own values?',
    },
    {
      id: 'discovery-30',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you are trying to make room for?',
    },
    {
      id: 'discovery-31',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a version of success that actually suits you?',
    },
    {
      id: 'discovery-32',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is the easiest way for someone to misunderstand you?',
    },
    {
      id: 'discovery-33',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one thing you are surprisingly sentimental about?',
    },
    {
      id: 'discovery-34',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a habit that helps you return to yourself?',
    },
    {
      id: 'discovery-35',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a small promise you try to keep to yourself?',
    },
    {
      id: 'discovery-36',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you have outgrown without making a dramatic announcement?',
    },
    {
      id: 'discovery-37',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is an experience you think made you more compassionate?',
    },
    {
      id: 'discovery-38',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is one topic you only open up about when the trust is real?',
    },
    {
      id: 'discovery-39',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is something you hope people feel after spending time with you?',
    },
    {
      id: 'discovery-40',
      category: 'discovery',
      categoryLabel: TOPIC_CATEGORIES.discovery,
      prompt: 'What is a question you would ask someone to understand how they love people?',
    },
    {
      id: 'hot-takes-01',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What harmless opinion would get you booed at a dinner table?',
    },
    {
      id: 'hot-takes-02',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What food is dramatically overrated, and why are people not ready for the truth?',
    },
    {
      id: 'hot-takes-03',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What film or show is good, but not as good as everyone insists?',
    },
    {
      id: 'hot-takes-04',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a common \'life hack\' that is mostly just extra admin?',
    },
    {
      id: 'hot-takes-05',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What everyday object deserves a public apology?',
    },
    {
      id: 'hot-takes-06',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is something people call classy that is actually just expensive beige?',
    },
    {
      id: 'hot-takes-07',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What song should be retired from public spaces for everyone\'s emotional safety?',
    },
    {
      id: 'hot-takes-08',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What snack is carrying society harder than it gets credit for?',
    },
    {
      id: 'hot-takes-09',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the worst seat in any restaurant, and why is it near the door?',
    },
    {
      id: 'hot-takes-10',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the most overrated weather?',
    },
    {
      id: 'hot-takes-11',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What hobby do people pretend is relaxing even though it is clearly warfare?',
    },
    {
      id: 'hot-takes-12',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a phrase people use when they are about to say absolutely nothing useful?',
    },
    {
      id: 'hot-takes-13',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What popular smell is secretly terrible?',
    },
    {
      id: 'hot-takes-14',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a breakfast item that has been coasting on reputation?',
    },
    {
      id: 'hot-takes-15',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a social rule that needs to be renegotiated immediately?',
    },
    {
      id: 'hot-takes-16',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What item of clothing has too much confidence?',
    },
    {
      id: 'hot-takes-17',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the most unfairly hated vegetable?',
    },
    {
      id: 'hot-takes-18',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the most overrated way to spend a Saturday?',
    },
    {
      id: 'hot-takes-19',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a tiny luxury people mock until they try it?',
    },
    {
      id: 'hot-takes-20',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the worst kind of small talk, and what should replace it?',
    },
    {
      id: 'hot-takes-21',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a drink order that tells you someone has main character energy?',
    },
    {
      id: 'hot-takes-22',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a chore that deserves more respect?',
    },
    {
      id: 'hot-takes-23',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a chore that should be automated by law?',
    },
    {
      id: 'hot-takes-24',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a dessert that understands the assignment every time?',
    },
    {
      id: 'hot-takes-25',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a restaurant trend that needs to calm down?',
    },
    {
      id: 'hot-takes-26',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a word people overuse until it loses all meaning?',
    },
    {
      id: 'hot-takes-27',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What animal has the most undeservedly good PR?',
    },
    {
      id: 'hot-takes-28',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the best crisp flavour, and how brave are you willing to be about it?',
    },
    {
      id: 'hot-takes-29',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is an office habit that belongs in a museum of pain?',
    },
    {
      id: 'hot-takes-30',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a holiday tradition that should be optional without judgement?',
    },
    {
      id: 'hot-takes-31',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a public transport etiquette crime you would prosecute gently but firmly?',
    },
    {
      id: 'hot-takes-32',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the most chaotic place to put a mirror?',
    },
    {
      id: 'hot-takes-33',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is something people call relaxing that actually feels like homework?',
    },
    {
      id: 'hot-takes-34',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a tiny inconvenience that reveals someone\'s true character?',
    },
    {
      id: 'hot-takes-35',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a modern design trend you want to have a word with?',
    },
    {
      id: 'hot-takes-36',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a kitchen item people buy with hope instead of evidence?',
    },
    {
      id: 'hot-takes-37',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a type of queue that should not exist in a civilised society?',
    },
    {
      id: 'hot-takes-38',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is a common date spot that is secretly a terrible idea?',
    },
    {
      id: 'hot-takes-39',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What is the most overrated form of productivity?',
    },
    {
      id: 'hot-takes-40',
      category: 'hot-takes',
      categoryLabel: TOPIC_CATEGORIES['hot-takes'],
      prompt: 'What opinion do you hold with zero evidence but complete confidence?',
    },
    {
      id: 'star-wars-01',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What subject would you absolutely dominate if it were part of Padawan training?',
    },
    {
      id: 'star-wars-02',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If your lightsaber colour was based on your texting style, what colour would it be?',
    },
    {
      id: 'star-wars-03',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What everyday task would become instantly cooler with a tiny floating training droid?',
    },
    {
      id: 'star-wars-04',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your Jedi Council nickname be if they based it on your worst habit?',
    },
    {
      id: 'star-wars-05',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your Force power be if the Force only helped with minor inconveniences?',
    },
    {
      id: 'star-wars-06',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which random subject would make you say, \'Strong opinions, I have\'?',
    },
    {
      id: 'star-wars-07',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If a Holocron roasted your dating profile, what would be its most accurate comment?',
    },
    {
      id: 'star-wars-08',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What is the most chaotic place to schedule a peaceful Jedi meditation retreat?',
    },
    {
      id: 'star-wars-09',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which Star Wars planet would you visit for a weekend, and which one is an immediate no?',
    },
    {
      id: 'star-wars-10',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would be your suspiciously specific droid function?',
    },
    {
      id: 'star-wars-11',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If your coffee order determined your allegiance, are you Jedi, Sith, or ungovernable smuggler?',
    },
    {
      id: 'star-wars-12',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What minor inconvenience would push you dangerously close to the dark side?',
    },
    {
      id: 'star-wars-13',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your cantina entrance music sound like?',
    },
    {
      id: 'star-wars-14',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which chore would you use the Force for even though Yoda would be disappointed?',
    },
    {
      id: 'star-wars-15',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If you had a droid companion, what personality flaw would it absolutely have?',
    },
    {
      id: 'star-wars-16',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What is the most dramatic thing you would say before losing a lightsaber duel immediately?',
    },
    {
      id: 'star-wars-17',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your Jedi robe look like if comfort mattered more than tradition?',
    },
    {
      id: 'star-wars-18',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which normal workplace meeting could be improved by a Jedi mind trick?',
    },
    {
      id: 'star-wars-19',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If your group chat were a rebel cell, what role would you play?',
    },
    {
      id: 'star-wars-20',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What snack would you smuggle across the galaxy at great personal risk?',
    },
    {
      id: 'star-wars-21',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If your car or bike had a hyperdrive, where is the first irresponsible place you would go?',
    },
    {
      id: 'star-wars-22',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would be the least useful Force vision to receive?',
    },
    {
      id: 'star-wars-23',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which Star Wars creature would make the worst flatmate?',
    },
    {
      id: 'star-wars-24',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What is your most Sith opinion about household chores?',
    },
    {
      id: 'star-wars-25',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If you trained a Padawan, what terrible life advice would accidentally slip out?',
    },
    {
      id: 'star-wars-26',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What everyday object has lightsaber energy despite not deserving it?',
    },
    {
      id: 'star-wars-27',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your personal starship be called if named after your current mood?',
    },
    {
      id: 'star-wars-28',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which ordinary task would make you dramatically say, \'This is where the fun begins\'?',
    },
    {
      id: 'star-wars-29',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If a bounty hunter tracked you, what embarrassingly normal clue would give you away?',
    },
    {
      id: 'star-wars-30',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your Jedi trial be if it was based on your biggest weakness?',
    },
    {
      id: 'star-wars-31',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which Star Wars character would be the best person to take to brunch?',
    },
    {
      id: 'star-wars-32',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would make you leave the Jedi Order, but in a very polite email?',
    },
    {
      id: 'star-wars-33',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If you could add one normal British thing to the Star Wars universe, what would improve it most?',
    },
    {
      id: 'star-wars-34',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What is the most romantic Star Wars date idea that would not immediately end in danger?',
    },
    {
      id: 'star-wars-35',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If your lightsaber made a sound based on your mood, what would it sound like today?',
    },
    {
      id: 'star-wars-36',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What droid would you trust with your secrets but not your calendar?',
    },
    {
      id: 'star-wars-37',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What would your rebel propaganda poster slogan be?',
    },
    {
      id: 'star-wars-38',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'Which planet would have the best food market?',
    },
    {
      id: 'star-wars-39',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'What is one thing the Jedi Council would definitely overthink about you?',
    },
    {
      id: 'star-wars-40',
      category: 'star-wars',
      categoryLabel: TOPIC_CATEGORIES['star-wars'],
      prompt: 'If the Force gave you one tiny dating advantage, what would be useful but not creepy?',
    },
  ],
};

export function selectRandomTopics(
  source: TopicSource = TOPIC_LIBRARY,
  count = 3,
  random: () => number = Math.random,
): Topic[] {
  if (count < 1) {
    return [];
  }

  const topicsByCategory = groupTopicsByCategory(source.topics);
  const categoryOrder = shuffle([...topicsByCategory.keys()], random);
  const selected: Topic[] = [];
  const usedIds = new Set<string>();

  for (const category of categoryOrder) {
    const options = topicsByCategory.get(category) ?? [];
    const topic = shuffle(options, random).find((candidate) => !usedIds.has(candidate.id));

    if (topic) {
      selected.push(topic);
      usedIds.add(topic.id);
    }

    if (selected.length === count) {
      return selected;
    }
  }

  for (const topic of shuffle(source.topics, random)) {
    if (!usedIds.has(topic.id)) {
      selected.push(topic);
      usedIds.add(topic.id);
    }

    if (selected.length === count) {
      return selected;
    }
  }

  return selected;
}

function groupTopicsByCategory(topics: readonly Topic[]): Map<TopicCategory, Topic[]> {
  return topics.reduce((groups, topic) => {
    const categoryTopics = groups.get(topic.category) ?? [];
    categoryTopics.push(topic);
    groups.set(topic.category, categoryTopics);

    return groups;
  }, new Map<TopicCategory, Topic[]>());
}

function shuffle<T>(items: readonly T[], random: () => number): T[] {
  return [...items]
    .map((item) => ({ item, sort: random() }))
    .sort((left, right) => left.sort - right.sort)
    .map(({ item }) => item);
}
